name: Python Release

on:
  workflow_call:
    inputs:
      wheels:
        description: "Build wheels for this release"
        required: true
        type: boolean
      cibw-skip:
        description: "Platforms to skip for cibuildwheel"
        required: false
        type: string
        default: "pp* *-win32 *-manylinux_i686 *-musllinux*"

    secrets:
      pypi-token:
        description: "A user token for uploading to PyPI"
        required: true
        type: string

jobs:
  sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Build sdist
        run: |
          python -m pip install -U pip
          python -m pip install -U build
          python -m build --sdist .
      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  wheels:
    if: ${{inputs.wheels}}
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Build wheels
        uses: pypa/cibuildwheel@2.7.0
        env:
          CIBW_SKIP: ${{inputs.cibw-skip}}
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"
      - name: Upload wheels as artifact
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  check_publish_sdist:
    if: ${{!inputs.wheels}}
    needs: sdist
    name: Publish source distribution
    uses: dfm/workflows/.github/workflows/python-publish.yml@main
    secrets:
      pypi-token: ${{secrets.pypi-token}}

  check_publish_full_dist:
    if: ${{inputs.wheels}}
    needs: [sdist, wheels]
    name: Publish source and wheels
    uses: dfm/workflows/.github/workflows/python-publish.yml@main
    secrets:
      pypi-token: ${{secrets.pypi-token}}
